[package]
name = "leanvm-xmss-c"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
test-config = ["lean-multisig/test-config", "leansig_wrapper/test-config"]

[dependencies]
lean-multisig = { git = "https://github.com/leanEthereum/leanMultisig.git", rev = "fd8814045deb0ef8fcad4c9f4b1250ee33f7dd01", package = "lean-multisig" }
leansig = { git = "https://github.com/leanEthereum/leanSig", branch = "devnet4" }
leansig_wrapper = { git = "https://github.com/leanEthereum/leanMultisig.git", rev = "fd8814045deb0ef8fcad4c9f4b1250ee33f7dd01", package = "leansig_wrapper" }
rand = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ssz = { package = "ethereum_ssz", version = "0.10" }

[build-dependencies]
cbindgen = "0.27"
