[package]
name = "leanvm-xmss-c"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator"]
test-config = ["rec_aggregation/test-config", "leansig_wrapper/test-config"]

[dependencies]
backend = { git = "https://github.com/leanEthereum/leanVM", rev = "e2592df4e30fdddbbf8ae26a333116c68cec7026" }
leansig = { git = "https://github.com/leanEthereum/leanSig", branch = "devnet4" }
leansig_wrapper = { git = "https://github.com/leanEthereum/leanVM", rev = "e2592df4e30fdddbbf8ae26a333116c68cec7026" }
rec_aggregation = { git = "https://github.com/leanEthereum/leanVM", rev = "e2592df4e30fdddbbf8ae26a333116c68cec7026" }
rand = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ssz = { package = "ethereum_ssz", version = "0.10" }
tikv-jemallocator = { version = "0.6", optional = true }

[build-dependencies]
cbindgen = "0.27"

[profile.multisig-release]
inherits = "release"
lto = "thin"
codegen-units = 1
